# Account Session

### Account Info After Login
GET http://localhost:3000/api/users/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJyaUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyIiwiaWF0IjoxNjY3Nzk4NzYwLCJleHAiOjE2Njc4Mjc1NjB9.IDumIlahrPS5iH7lItVvKBMEGsjKEJNP2oqfe76j-yA

### Get All Account
GET http://localhost:3000/api/users

### Add Account
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "email": "ri@gmail.com",
    "password": "12"
}

### Update Account
PUT http://localhost:3000/api/users
Content-Type: application/json

{
    "id": "3",
    "email": "inihasiledit@gmail.com",
    "password": "123"
}

### Delete Account
DELETE http://localhost:3000/api/users/3





# Tracker Session

### Get Expense Based on LogIn Account
GET http://localhost:3000/api/tracker
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJyaUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyIiwiaWF0IjoxNjY3ODI5NTIyLCJleHAiOjE2Njc4NTgzMjJ9.Bh1lSVRdw57KoCpvN23UBaTXeXDEolTgsnDHurG6K2c

### Add Expense to Login Account
POST http://localhost:3000/api/tracker
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJyaUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyIiwiaWF0IjoxNjY3ODI5NTIyLCJleHAiOjE2Njc4NTgzMjJ9.Bh1lSVRdw57KoCpvN23UBaTXeXDEolTgsnDHurG6K2c
Content-Type: application/json

{
    "type": "outcome",
    "expense": 20000,
    "description": "beli mouse"
}

### LogIn Account
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "ri@gmail.com",
    "password": "12"
}

